### ISSUE TITLE
incorrect default value for 'port' option

### ISSUE THREAD

**Issue by stefanorg** [zendframework/zend-ldap#19]
Hi,
according to the documentation the  [Server Options](http://framework.zend.com/manual/current/en/modules/zend.authentication.adapter.ldap.html#server-options) 'port' parameter say: 
>The port on which the LDAP server is listening. If useSsl is TRUE, the default port value is 636. If useSsl is FALSE, the default port value is 389.

with the following code:

```
$options = [
                'host' => 's0.foo.net',
//                'port' => '389',
                'useStartTls' => 'false',
                'accountDomainName' => 'foo.net',
                'accountDomainNameShort' => 'FOO',
                'accountCanonicalForm' => '4',
                'baseDn' => 'CN=user1,DC=foo,DC=net',
                'allowEmptyPassword' => false
            ]
$ldap = new Ldap($options);
$ldap->bind('myuser','mypwd')
```
i get the exception: `Failed to connect to LDAP server: s0.foo.net:0`

```
exception 'Zend\Ldap\Exception\LdapException' with message 'Failed to connect to LDAP server: s0.foo.net:0' in /home/dockerdev/app/vendor/zendframework/zend-ldap/src/Ldap.php:748
Stack trace:
#0 /home/dockerdev/app/vendor/zendframework/zend-ldap/src/Ldap.php(812): Zend\Ldap\Ldap->connect()
#1 /home/dockerdev/app/module/DipvvfModule/src/DipvvfModule/Check/LdapServiceCheck.php(57): Zend\Ldap\Ldap->bind('intranet@no.dip...', 'Intr4n3t101177!')
#2 /home/dockerdev/app/vendor/zendframework/zenddiagnostics/src/ZendDiagnostics/Runner/Runner.php(123): DipvvfModule\Check\LdapServiceCheck->check()
#3 /home/dockerdev/app/vendor/zendframework/zftool/src/ZFTool/Diagnostics/Runner.php(43): ZendDiagnostics\Runner\Runner->run(NULL)
#4 /home/dockerdev/app/vendor/zendframework/zftool/src/ZFTool/Controller/DiagnosticsController.php(234): ZFTool\Diagnostics\Runner->run()
#5 /home/dockerdev/app/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): ZFTool\Controller\DiagnosticsController->runAction()
#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /home/dockerdev/app/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /home/dockerdev/app/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /home/dockerdev/app/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /home/dockerdev/app/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Console\Request), Object(Zend\Console\Response))
#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /home/dockerdev/app/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /home/dockerdev/app/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /home/dockerdev/app/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /home/dockerdev/app/tools/zf.php(53): Zend\Mvc\Application->run()
#16 {main}
```

if we uncomment the 'port' option everything work fine.

**Comment by heiglandreas** [comment]
Thanks for reporting the issue.

But I'm sorry to have to tell you that I fail to reproduce this issue. Can you give us some more details about the environment you are running in? PHP-Version, Zend-LDAP-Version and server-system would be a good start.

I've created an example-testcase as follows which runs into an exception as the specified server actually can't be reached. But that's a totaly different Message than the one you described.

```php
<?php
namespace ZendTest\Ldap;

use Zend\Ldap;
use Zend\Ldap\Exception;

class ConnectionTest extends \PHPUnit_Framework_TestCase
{
    public function testConnectionWithOptionsArray()
    {
        $options = [
            'host' => 's0.foo.net',
            'port' => '389',
            'useStartTls' => 'false',
            'accountDomainName' => 'foo.net',
            'accountDomainNameShort' => 'FOO',
            'accountCanonicalForm' => '4',
            'baseDn' => 'CN=user1,DC=foo,DC=net',
            'allowEmptyPassword' => false
        ];

        try {
            $ldap = new \Zend\Ldap\Ldap($options);
            $this->assertInstanceof('\Zend\Ldap\Ldap', $ldap);
            $ldap->bind('user', 'pass');
        } catch(Exception\LdapException $e) {
            $this->fail($e->getMessage());
        }
    }
}
```

results in this output:

```bash
$ phpunit --filter ConnectionTest
PHPUnit 4.7.6 by Sebastian Bergmann and contributors.

F

Time: 1.6 seconds, Memory: 22.00Mb

There was 1 failure:

1) ZendTest\Ldap\ConnectionTest::testConnectionWithOptionsArray
0x51 (Can't contact LDAP server): ldap://s0.foo.net:389

/Users/Shared/Development/Sites/zend-ldap/test/ConnectionTest.php:27
```

That's something completely different than your described ```Failed to connect to LDAP server: s0.foo.net:0```. There the port is set to ```0```  which is not a valid port and therefore the ```connect()```-method fails. So the main question is **why is your port set to 0 when you specify a port**. Could it be possible that your port-string contains an invalid, invisible character that can not be converted to *int*? As the port-parameter is cast to int that might cause a ```0``` to appear. 

Would you be so kind as to check whether setting the port as integer has the same effect? It will be cast to int during the creation of the LDAP-Object.

**Comment by stefanorg** [comment]
Hi thanks for your reply.

As i say before, the port option is commented, because i expect that it takes the default value as described in documentation but it doesn't.

If i uncomment the option, explicitly setting the port to 389 everything work fine.

If i understand correctly as said in doc:

>The port on which the LDAP server is listening. If useSsl is TRUE, the default port value is 636. If useSsl is FALSE, the default port value is 389.

Maybe the default value in (setOptions)[https://github.com/zendframework/zend-ldap/blob/master/src/Ldap.php#L226] has to be 389 or we need to change the method (getPort)[https://github.com/zendframework/zend-ldap/blob/master/src/Ldap.php#L302] to consider the the useSsl option, something like

```
public function getOptions() {
 // if port is 0 choose the right default value based on useSsl or useStartTls
....
}
```

**Comment by heiglandreas** [comment]
Sorry, I missunderstood you there! When I comment out the port-part of the configuration I do get the same error as you!

Investigating!
