### ISSUE TITLE
Set dependency for PHPUnit right

### ISSUE THREAD

**Issue by heiglandreas** [zendframework/zend-ldap#23]
PHPUnit needs to use the 4-branch for PHP5.5 and the 5-branch for PHP7. So for testing we have to adapt the requirement to PHPUnit (and possibly other libs as well) to reflect that.

There is a solution to that on https://github.com/zendframework/zend-ldap/pull/21#discussion_r44708832

**Comment by ThaDafinser** [comment]
@heiglandreas i used this [here](https://github.com/ThaDafinser/UserAgentParser/blob/master/composer.json#L82)

I still dont like that kind of dependency, because it can lead to different PHPUnit outputs, or you may get errors very late, because it's a PHPUnit4 problem.

But it works ... :+1:

**Comment by heiglandreas** [comment]
I don't say I like it :wink:. But currently I've set PHPUnit 5 as requirement and on travis I change it tho PHPUnit 4.* when running in PHP5.5. 

That will cause the tests to run on Travis under PHP5.5 but everyone else trying that will have to do some debugging themselves when the unit-tests don't work… 

Therefore I Think that's the best solution there is (apart from moving the dependencies to PHP7 only :wink:)

**Comment by heiglandreas** [comment]
This is fixed with #43

**Comment by heiglandreas** [comment]
This has been fixed with release 2.7.0
