### ISSUE TITLE
Remove the call to ldap_sort from Zend\Ldap\Ldap::search

### ISSUE THREAD

**Issue by heiglandreas** [zendframework/zend-ldap#3]
Currently ```Zend\Ldap\Ldap::search()``` internally calls ```ldap_sort``` which is already deprecated in the OpenLDAP-libraries and will become deprecated in PHP. As the sorting only is done client-sided and we can not be sure that there might be other data on the server that should be in between the sorting is not really meaningfull. 

We should look for a way to sort the data with the "default" PHP-sorting-functions

**Comment by Maks3w** [comment]
PHP7 run is start to failling due this deprecation. Any volunteer for to fix this?

**Comment by heiglandreas** [comment]
already had a look at it so if no one else steps up I'll check it. Seems fair as I introduced the deprecated-message :wink:

-- 
Andreas Heigl
Andreas@heigl.org

**Comment by mwillbanks** [comment]
changed milestone and closing ticket as this is committed in develop.
