### ISSUE TITLE
PHP7 release

### ISSUE THREAD

**Issue by ThaDafinser** [zendframework/zend-ldap#30]
Hello together,

to move to PHP7 the PR #16 from @heiglandreas is needed to avoid the `deprecation` warning.

Is it possible to release a new tag in the next time?

**Comment by heiglandreas** [comment]
Hi @ThaDafinser 

I've got it on my agenda for a far too long time! Hope to get to it this week!

**Comment by ThaDafinser** [comment]
Great! Thank you in advance

**Comment by ThaDafinser** [comment]
Any progress on this? :+1:

**Comment by heiglandreas** [comment]
... :disappointed: not yet...

**Comment by heiglandreas** [comment]
Here we go! [Release 2.6.0](https://github.com/zendframework/zend-ldap/releases/tag/release-2.6.0) is out!

**Comment by ThaDafinser** [comment]
Thank you :+1:
