### ISSUE TITLE
No wrapper for ldap_mod_del()

### ISSUE THREAD

**Issue by caseyfw** [zendframework/zend-ldap#4]
Forgive me if I'm missing something, but I can't seem to remove a user from a group using this library, or at least in a manner similar to that used in the contrib notes on this page: http://php.net/manual/en/function.ldap-mod-del.php

**Comment by ThaDafinser** [comment]
@caseyfw you can (as a workaround) do this:

```php
$ldap = new \Zend\Ldap\Ldap(...);
$res = $ldap->getResource();

ldap_mod_del($res, ...);
```

**Comment by Maks3w** [comment]
Merged #6

**Comment by caseyfw** [comment]
![Woohoo!](http://img3.wikia.nocookie.net/__cb20121125043652/adventuretimesuperfans/images/f/f7/Jake_sparkly_eyes.gif)

**Comment by martinjinda** [comment]
Hi, 

I try use `ldap_mod_del()` as is describe above, but it doesn't work. But if I use this workaround with `ldap_mod_add` it works fine.

I always get following error:
`ldap_mod_del(): Modify: No such attribute (2)`
