### ISSUE TITLE
Escape LDAP with ldap_escape()

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-ldap#51]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7521
User: @Maks3w
Created On: 2015-05-14T06:43:14Z
Updated At: 2015-06-03T17:28:47Z
Body
Since PHP 5.6 the function [ldap_escape](http://php.net/manual/en/function.ldap-escape.php) allow escape input contextually for FILTER and DN.

This could be an improvement over the current manual process

https://github.com/zendframework/zf2/blob/master/library/Zend/Ldap/Filter/AbstractFilter.php#L86
https://github.com/zendframework/zf2/blob/master/library/Zend/Ldap/Converter/Converter.php#L35

Polyfill http://stackoverflow.com/a/8561604/1163444

---

**Comment by KaelBaldwin** [comment]
Just FYI, Our company is currently having issues with the current manner of escaping filters, specifically guids. One or two guid's cause a bad filter error. I adjusted the code to use the ldap_escape() function and that fixed the problem. We will be creating our own create filter method to use until this is resolved.

**Comment by heiglandreas** [comment]
Thanks for the feedback! Would you mind opening a PR?

**Comment by KaelBaldwin** [comment]
will do

**Comment by heiglandreas** [comment]
Thad'd be absolutely awesome! Thanks!

**Comment by KaelBaldwin** [comment]
Hopefully did that correctly: #52
I'm a bit of a new developer, fair warning, but the change was minor.
All this does is change the filter value escaping method to use ldap_escape(), so the escaping of dn's is not handled by this PR.
phpunit test of Filter.php ran without problems.

**Comment by KaelBaldwin** [comment]
Actually pretty sure I did that incorrectly. This needs to go to the develop branch then correct? Incompatible with php5.5 obviously as ldap_escape() was added in php5.6 so that check was failed.

**Comment by weierophinney** [comment]
@KaelBaldwin Next minor release will be using PHP 5.6 as the minimum supported version (heads-up to you, @heiglandreas !).

**Comment by heiglandreas** [comment]
Thanks for that Info. That will make it much easier :)

I'll dig through the PR tomorrow. And then we'll sort everything out. No need to worry. 

Thanks for the contribution!

**Comment by KaelBaldwin** [comment]
Sure thing!
