### ISSUE TITLE
ldap_mod_replace() ?

### ISSUE THREAD

**Issue by mbaynton** [zendframework/zend-ldap#67]
It seems as if one of the primitive ldap CRUD operations, manifested in the php API as ldap_mod_replace(), is not wrapped by zend-ldap. Is this an intentional omission for some reason? I can add it if not.

**Comment by heiglandreas** [comment]
The attribute-related operations have only been added recently. And the replace-functionality just wasn'T asked for yet :)

If you'd like to give it a go that'd be great! Perhaps you want to have a look at https://github.com/zendframework/zend-ldap/blob/master/src/Ldap.php#L1326 for inspiration.
