### ISSUE TITLE
Enable LDAP-Testing on TravisCI

### ISSUE THREAD

**Issue by heiglandreas** [zendframework/zend-ldap#7]
Currently most of the tests are skipped on travis as they require testing against an existing LDAP.

This PR enables an LDAP-Server on Travis to run the tests again so that only 4 tests of the testsuite are currently skipped.

**Comment by gianarb** [comment]
What do you mean? :) This component is already enabled on travis :)

**Comment by heiglandreas** [comment]
Yeah, it was. But it did skip most of the tests due to a missing LDAP-Server to test against :wink: But It seems that I've been too occupied dividing the two PRs I did yesterday that I missed adding a PR-Message :frowning: 

I've added that now to explain better what's this about. :wink:

**Comment by weierophinney** [comment]
This isn't a PR... it's an issue. I'm assuming #8 is the actual PR, and, as such, I'm closing this to keep discussion there.
